# Generated by Django 5.0.6 on 2024-07-16 10:58

import config.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_follow_created_at_alter_follow_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='follow',
            name='id',
            field=config.utils.CustomAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=config.utils.CustomAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
