# Generated by Django 5.0.6 on 2024-07-08 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tagged_users',
            field=models.ManyToManyField(db_index=True, related_name='tagged_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
