# Generated by Django 5.0.6 on 2024-08-02 11:26

import config.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_comment_post_comment_text'),
        ('content', '0002_post_banner_post_main_tag'),
        ('content_plan', '0002_contentplan_trial_description_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedpost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='savedpost',
            name='user',
        ),
        migrations.AlterModelTable(
            name='like',
            table='content_likes',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='content_tags',
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', config.utils.CustomAutoField(editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255, null=True)),
                ('media', models.FileField(upload_to='contents/')),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('text', 'Text'), ('image', 'Image')], max_length=10)),
                ('banner', models.FileField(null=True, upload_to='banners/')),
                ('type', models.CharField(choices=[('content', 'Content'), ('message', 'Message')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='content_plan.contentplan')),
                ('main_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_contents', to='content.tag')),
                ('tagged_users', models.ManyToManyField(db_index=True, related_name='tagged_contents', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(db_index=True, related_name='contents', to='content.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'content',
                'verbose_name_plural': 'contents',
                'db_table': 'contents',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='like',
            name='content',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='content.content'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SavedContent',
            fields=[
                ('id', config.utils.CustomAutoField(editable=False, primary_key=True, serialize=False)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='content.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'saved content',
                'verbose_name_plural': 'saved contents',
                'db_table': 'content_saved',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='SavedPost',
        ),
    ]
