# Generated by Django 5.0.6 on 2024-07-16 10:58

import config.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_post_content_plan_alter_like_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='like',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='savedpost',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='savedpost',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=config.utils.CustomAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=config.utils.CustomAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='savedpost',
            name='id',
            field=config.utils.CustomAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=config.utils.CustomAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
