# Generated by Django 5.0.6 on 2024-08-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_savedpost_post_remove_like_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='media_aspect_ratio',
            field=models.DecimalField(decimal_places=7, max_digits=15, null=True),
        ),
    ]
