# Generated by Django 5.0.6 on 2024-08-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_content_media_aspect_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='media',
            field=models.FileField(null=True, upload_to='contents/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='media_type',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('text', 'Text'), ('image', 'Image')], max_length=10, null=True),
        ),
    ]
