# Generated by Django 5.0.6 on 2024-08-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_content_media_alter_content_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='media_aspect_ratio',
            field=models.FloatField(null=True),
        ),
    ]
