# Generated by Django 5.1.1 on 2024-09-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_contentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='thumbnail',
            field=models.FileField(null=True, upload_to='contents/thumbnails/'),
        ),
    ]
