# Generated by Django 5.1.1 on 2024-09-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_content_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='media_preview',
            field=models.FileField(null=True, upload_to='contents/'),
        ),
    ]
