# Generated by Django 5.0.6 on 2024-08-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='Salom Shahob'),
            preserve_default=False,
        ),
    ]
