# Generated by Django 5.0.6 on 2024-08-02 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_comment_post_comment_text'),
        ('content', '0003_remove_savedpost_post_remove_like_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.content'),
        ),
    ]
