# Generated by Django 5.0.6 on 2024-07-16 10:58

import config.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_created_at_alter_comment_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=config.utils.CustomAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
