# Generated by Django 5.0.6 on 2024-09-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_delete_fcmtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('follow', 'Follow'), ('content', 'Content'), ('mention', 'Mention')], max_length=10),
        ),
    ]
