# Generated by Django 5.0.6 on 2024-06-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(db_index=True, related_name='posts', to='posts.tag'),
        ),
    ]
