# Generated by Django 5.0.6 on 2024-07-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_plan', '0002_alter_contentplan_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentplan',
            name='status',
        ),
        migrations.AddField(
            model_name='contentplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
