# Generated by Django 5.0.6 on 2024-07-16 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_plan', '0003_remove_contentplan_status_contentplan_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentplan',
            options={'ordering': ('created_at',), 'verbose_name': 'content plan', 'verbose_name_plural': 'content plans'},
        ),
    ]
