# Generated by Django 5.0.6 on 2024-07-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_plan', '0004_alter_contentplan_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentplan',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
