# Generated by Django 5.0.6 on 2024-07-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_plan', '0005_alter_contentplan_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentplan',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contentplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contentplan',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='contentplan',
            name='trial_days',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contentplan',
            name='trial_discount_percent',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
