# Generated by Django 5.0.6 on 2024-07-16 10:58

import config.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_plan', '0006_alter_contentplan_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentplan',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='contentplan',
            name='id',
            field=config.utils.CustomAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
