# Generated by Django 5.0.6 on 2024-08-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='image',
            field=models.ImageField(null=True, upload_to='chats/images/'),
        ),
    ]
