# Generated by Django 5.0.6 on 2024-07-16 10:58

import config.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_created_at_alter_chat_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=config.utils.CustomAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=config.utils.CustomAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
