# Generated by Django 5.0.6 on 2024-08-09 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsetting',
            options={'verbose_name': 'chat setting', 'verbose_name_plural': 'chat settings'},
        ),
        migrations.RemoveField(
            model_name='chatsetting',
            name='created_at',
        ),
    ]
