# Generated by Django 5.0.6 on 2024-08-10 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chatsetting_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='request_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
