# Generated by Django 5.0.6 on 2024-08-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chat_is_request_chat_request_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media_aspect_ratio',
            field=models.FloatField(null=True),
        ),
    ]
