# Generated by Django 5.0.6 on 2024-09-05 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_message_media_aspect_ratio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-created_at',), 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
    ]
