# Generated by Django 5.1.1 on 2024-09-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='thumbnail',
            field=models.FileField(null=True, upload_to='messages/media/'),
        ),
    ]
